How many negative numbers are there?

In [1]:
import numpy as np #industry standard

In [173]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [174]:
mask = a < 0
mask

array([False, False, False, False,  True,  True, False, False, False,
        True, False,  True])

In [175]:
len(a[mask])

4

How many positive numbers are there?

In [49]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [50]:
mask = a > 0
mask

array([ True,  True,  True,  True, False, False, False, False, False,
       False,  True, False])

In [51]:
a[mask]

array([ 4, 10, 12, 23,  3])

How many even positive numbers are there?

In [19]:
a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [22]:
mask = (a > 0) & (a % 2 == 0) #have to use & because we are compairing two arrays
mask

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False])

In [23]:
a[mask]

array([ 4, 10, 12])

If you were to add 3 to each data point, how many positive numbers would there be?

In [57]:
a = a + 3

In [58]:
a

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

In [59]:
mask = a > 0
mask

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True, False])

In [60]:
a[mask]

array([ 7, 13, 15, 26,  1,  2,  3,  3,  3,  6])

If you squared each number, what would the new mean and standard deviation be?

In [151]:
# a = a ** 2
# a

In [66]:
a_squared.mean()

74.0

In [67]:
a_squared.std()

144.0243035046516

A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean from each data point. Center the data set. See this link for more on centering.



In [75]:
a = a - a.mean()
a

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [77]:
a.mean()

0.0

Calculate the z-score for each data point. Recall that the z-score is given by:

In [82]:
import scipy.stats as stats

In [84]:
stats.zscore(a)

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.

In [172]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = sum(a)
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a)
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = np.mean(a)
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = np.prod(a)
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = [x**2 for x in a]
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = [x for x in a if x % 2 != 0]
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = [x for x in a if x % 2 == 0]
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

    
np.sum(b)
# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  


np.min(b)
# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

np.max(b)
# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))


np.mean(b)
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number

        
np.prod(b)
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)


np.square(b)
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)


# b[b % 2 != 0]
# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)


#b [b % 2 == 0]
# Exercise 9 - print out the shape of the array b.
# b.shape
# Exercise 10 - transpose the array b.
#np.transpose(b)
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
#np.reshape(b, (1,6))
#b.flatten()
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
#np.reshape(b, (6,1))
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.
#c.min(), c.max(), c.sum(), c.prod()
# Exercise 2 - Determine the standard deviation of c.
#c.std()
# Exercise 3 - Determine the variance of c.
#c.var()
# Exercise 4 - Print out the shape of the array c
#c.shape #attribute no paranthesis needed
# Exercise 5 - Transpose c and print out transposed result.
#c.T
# Exercise 6 - Get the dot product of the array c with c. 
#np.dot(c, c)
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261
#(c.T * c).sum()
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.
#(c.T * c).prod()

## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

d = np.array(d)
d
# Exercise 1 - Find the sine of all the numbers in d
np.sin(d)
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)
# Exercise 3 - Find the tangent of all the numbers in d
np.tan(d)
# Exercise 4 - Find all the negative numbers in d
d [d < 0]
# Exercise 5 - Find all the positive numbers in d
d [d > 0]
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)
# Exercise 7 - Determine how many unique numbers there are in d.
len(np.unique(d))
# Exercise 8 - Print out the shape of d.
d.shape
# Exercise 9 - Transpose and then print out the shape of d.
d.T.shape
# Exercise 10 - Reshape d into an array of 9 x 2
np.reshape(d, (9,2))

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])

In [157]:
np.array(b)

array([[3, 4, 5],
       [6, 7, 8]])

In [153]:
my_array.shape

(2, 3)

In [160]:
#b[b % 2 != 0]